baseURL = "http://xxquan.org/"
languageCode = "zh-CN"
title = "信息圈 导航 记录 知识星球"
theme = "webstack"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "xxquan.org"
  description = "xxquan"

[params.darkmode]
  enable = true



googleAnalytics = "G-JW0XD66PK7"